name: Generate Snake Game

# Gatilhos: agendamento e execução manual
on:
  schedule:
    # Executa a cada 24 horas (meia-noite UTC)
    - cron: "0 0 * * *" 
  workflow_dispatch:

# Permissão necessária para gravar no repositório
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Gera os arquivos SVG do Snake
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      # 3. Faz o push dos arquivos para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}